project_id = "xlmtucojkefacqqgbvra"

[functions.sourcing-ia]
verify_jwt = false

[functions.improve-candidate-summary]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false
